service: phoneforyou-cart-service

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  stage: dev
  runtime: nodejs18.x
  timeout: 15
  memorySize: 512
  region: eu-central-1

custom:

functions:
  main:
    handler: dist/handler.handler
    url: true
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
